version: "3.8"

services:
  postgres:
    image: postgres
    volumes:
      - postgresdata:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db

volumes:
  postgresdata: